run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true

linters:
  disable-all: true
  enable:
    # 🔴 MUST
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

    # 🟡 QUALITY
    - revive
    - gosimple
    - goconst
    - misspell
    - unconvert
    - unparam

    # 🟠 DB / backend (ВАЖНО для Postgres)
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - noctx
    - prealloc

    # 🔵 STYLE
    - gofmt
    - goimports
    - lll

    # 🟣 COMPLEXITY
    - gocyclo

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: early-return

  gocyclo:
    min-complexity: 12

  goconst:
    min-len: 3
    min-occurrences: 3

  lll:
    line-length: 120

  misspell:
    locale: US

  govet:
    enable:
      - shadow

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # тесты не душим
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck

    # db слой часто шумит по стилю
    - path: internal/db/
      linters:
        - revive
