run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  govet:
    enable-all: true
  lll:
    line-length: 140

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

service:
  golangci-lint-version: 1.60
