FROM golang:1.26-alpine

RUN apk add --no-cache git && mkdir -p /app/tmp /app/src

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

ENV GOPATH=/go
ARG MAKEFLAGS="-j1"

COPY . .

CMD ["air", "-c", "air.toml"]
